# for local development
version: "3.7"

services:
  quasar:
    build:
      context: .docker/
      target: "develop-stage"
    ports:
      - "8080:8080"
    volumes:
      - ".:/src"
    command: /bin/sh -c "yarn && quasar dev"
